<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyTitle>MesaShield</AssemblyTitle>
    <Product>MesaShield Security</Product>
    <Version>0.21.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MesaShield.Core\MesaShield.Core.csproj" />
    <ProjectReference Include="..\MesaShield.Windows\MesaShield.Windows.csproj" />
  </ItemGroup>

</Project>
