<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Description>MesaShield Windows integration: real-time protection, process watch, firewall manager.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MesaShield.Core\MesaShield.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.9" />
  </ItemGroup>

</Project>
